

= AWS Systems Manager (SSM)
Diego Canizales <diego.canizales1995@gmail.com>
1.0, October 11, 2020

https://docs.aws.amazon.com/systems-manager/latest/userguide/what-is-systems-manager.html

== SSM Introduction

Is a resource that you can use to view and control your infrastructure on AWS. Using the SSM console, you can view operational data from multiple AWS services and automate operational tasks across your AWS resources.

It provides reporting (or taking corrective action), on any policy violation it detects.


A *managed instance* is a machine that has been configured for use with SSM.


Supports:
* EC2 instances
* On-premises servers
* VMs in other cloud environments


Using SSM you can group your AWS resources together, by applaying the same identifying _resource tag_ to them. You can then view them all as a _group_.



=== Example

You can use SSM to assign a resource tag of "Operation=North Region OS Patching" to all of the following resources:

* A group of EC2 instances
* A group of on-premises servers in you own facility
* A SSM baseline that specifies which patches to apply to your managed instances
* An S3 bucket to store patching operation log output
* A SSM _maintenance window_ that specifies the schedule for the patching operation.


You can then view a really cool *consolidated dashboard* in SSM that reports the status of all the resources that are part of the group!.

=== Capabilities

SSM has five (5) goals:

. Operations Management
. Application Management
. Actions & Change
. Instances & Nodes
. Shared Resources


=== SSM Parameter store

Provides secure, hierarchical storage for configuration data management, and secrets management. 

You can store:

. Passwords
. Database strings
. *Amazon Machine Image  (AMI)*
. License codes


You can store them as:
* plain text
* encrypted data
